### ISSUE TITLE
[Question] Why certain characters are escaped?

### ISSUE THREAD

**Issue by MaicolBen** [yury/gsm_encoder#8]
Hi!

If I do `GSMEncoder.encode('$')` it retrieves `"\x02"`. Why is that? '$' is included in [GSM 03.38](https://en.wikipedia.org/wiki/GSM_03.38).

Thanks,

Maicol

**Comment by squidpunch** [comment]
I believe it's because that is the encoded value:

```ruby
GSMEncoder.can_encode?('$')
=> true

GSMEncoder.decode(GSMEncoder.encode('$'))
=> "$"
````

versus something that is not within the spec

```ruby
GSMEncoder.can_encode?('`')
=> false

GSMEncoder.decode(GSMEncoder.encode('`'))
=> "?"
```

**Comment by MaicolBen** [comment]
Thanks @squidpunch, I didn't know that I've to decode once I encoded.

**Comment by squidpunch** [comment]
@MaicolBen happy to help!

**Comment by yury** [comment]
Thanks @squidpunch
